"""Source-independent EFC geometry shared by training and detached runtime."""

from episode_functor_machine import MAX_ACTIONS, MAX_OBSERVERS, MAX_STATES


BYTE_PAD_ID = 256
MAX_UNIQUE_KEYS = MAX_STATES + MAX_ACTIONS + MAX_OBSERVERS
PRIMARY_STATES = 8
PRIMARY_ACTIONS = 3
PRIMARY_OBSERVERS = 2
PRIMARY_ANSWERS = 4
PRIMARY_KEYS = PRIMARY_STATES + PRIMARY_ACTIONS + PRIMARY_OBSERVERS


__all__ = [
    "BYTE_PAD_ID",
    "MAX_UNIQUE_KEYS",
    "PRIMARY_ACTIONS",
    "PRIMARY_ANSWERS",
    "PRIMARY_KEYS",
    "PRIMARY_OBSERVERS",
    "PRIMARY_STATES",
]
